apiVersion: v1
kind: Service
metadata:
  name: dns
  labels:
    name: dns
spec:
  type: ClusterIP
  ports:
    - protocol: UDP
      port: 53
      name: udpport
    - protocol: TCP
      port: 53
      name: tcpport
  externalIPs:
    - 192.168.1.3
  selector:
    name: dns
