apiVersion: v1
kind: ReplicationController
metadata:
  name: dns
  labels:
    name: dns
spec:
  replicas: 3
  selector:
    name: dns
  template:
    metadata:
      labels:
        name: dns
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: dns
        image: jon451994/dns
        imagePullPolicy: "Always"
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
