apiVersion: v1
kind: Service
metadata:
  name: dovecot
  labels:
    name: dovecot
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 24
      name: tcpportlmtp
    - protocol: TCP
      port: 143
      name: tcpportimap
    - protocol: TCP
      port: 12345
      name: tcpportsasl
  externalIPs:
    - 192.168.1.3
  selector:
    name: dovecot
