apiVersion: v1
kind: ReplicationController
metadata:
  name: dovecot
  labels:
    name: dovecot
spec:
  replicas: 1
  selector:
    name: dovecot
  template:
    metadata:
      labels:
        name: dovecot
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: dovecot
        image: jon451994/dovecot
        imagePullPolicy: "Always"
        ports:
        - containerPort: 24
          protocol: TCP
        - containerPort: 143
          protocol: TCP
        - containerPort: 12345
          protocol: TCP
