apiVersion: v1
kind: ReplicationController
metadata:
  name: postfix
  labels:
    name: postfix
spec:
  replicas: 3
  selector:
    name: postfix
  template:
    metadata:
      labels:
        name: postfix
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: postfix
        image: jon451994/postfix
        imagePullPolicy: "Always"
        ports:
        - containerPort: 25
          protocol: TCP
