apiVersion: v1
kind: Service
metadata:
  name: postfix
  labels:
    name: postfix
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 25
      name: tcpport
  externalIPs:
    - 192.168.1.3
  selector:
    name: postfix
