apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      name: tcpport
  externalIPs:
    - 192.168.1.3
  selector:
    name: web
