apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
spec:
  replicas: 3
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: web
        image: jon451994/web
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
          protocol: TCP
